name: Push to personal github account
on:
  push:
    branches: [main]

jobs:
  pushit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: push to main branch of personal account
        uses: cpino/github-action-push-to-another-repository
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ''
          destination-github-user: 'IVainqueur'
          destination-repository-name: 'eKOSORA_backend'
          user-email: ishimvainqueur@gmail.com
          target-branch: main
